# fly.toml app configuration file generated for portfolio-test-image-purple-dream-7022-snowy-forest-1336 on 2024-01-15T16:34:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portfolio-test-image-purple-dream-7022-snowy-forest-1336"
primary_region = "lhr"

[deploy]
  wait_timeout = "10m"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
