# fly.toml app configuration file generated for portfolio-test-image-purple-dream-7022 on 2024-01-15T13:46:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portfolio-test-image-purple-dream-7022"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
